services:
  - docker

before_install:
  - docker pull hashicorp/terraform:0.11.14

script:
  - docker run -i -v $(pwd):/app -w /app/terraform-lambda -t hashicorp/terraform:0.11.14 init
  - docker run -i -v $(pwd):/app -w /app/terraform-lambda -t hashicorp/terraform:0.11.14 validate