services:
  - docker

env:
  global:
  - DOCKER_TERRAFORM=hashicorp/terraform:0.11.14
  - DIR_TERRAFORM=terraform-lambda

before_install:
  - docker pull $DOCKER_TERRAFORM
  - docker run -i -v $(pwd):/app -w /app/$DIR_TERRAFORM -t $DOCKER_TERRAFORM init

jobs:
  include:
    - stage: Tests
      script:
        - docker run -i -v $(pwd):/app -w /app/$DIR_TERRAFORM -t $DOCKER_TERRAFORM validate
    - stage: Build
      script:
        - docker run -i -v $(pwd):/app -w /app/$DIR_TERRAFORM -t $DOCKER_TERRAFORM plan
    - stage: Deploy
      script:
        - docker run -i -v $(pwd):/app -w /app/$DIR_TERRAFORM -t $DOCKER_TERRAFORM apply